name: pytask-r

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.1.0
  - pytask-parallel >=0.1.0
  - r-base

  # Misc
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - black

  - pip:
    - -e .
