name: pytask-r

channels:
  - conda-forge
  - conda-forge/label/pytask_rc
  - conda-forge/label/pytask_parallel_rc
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask >=0.4.0rc4
  - pytask-parallel >=0.4.0rc1

  - r-base >4
  - r-jsonlite
  - r-yaml

  # Misc
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - black

  - pip:
    - -e .
