name: pytask-r

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.3
  - pytask-parallel >=0.3

  - r-base >4
  - r-jsonlite
  - r-yaml

  # Misc
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - black

  - pip:
    - -e .
