name: pytask-r

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.0.9
  - pytask-parallel >=0.0.4
  - r-base

  # Misc
  - bumpversion
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - versioneer
  - black
