name: pytask-r
channels:
  - conda-forge
  - r
  - pytask
dependencies:
  - python=3.7
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >= 0.0.4
  - r-base

  # Misc
  - bumpversion
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest-cov
  - pytest-xdist
