{% set data = load_setup_py_data() %}

package:
  name: pytask-r
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python >=3.6
    - pytask >=0.0.7

test:
  requires:
    - pytest
    - r-base
  source_files:
    - tox.ini
    - tests
  commands:
    - pytask --version
    - pytask --help
    - pytask markers
    - pytask clean

    - pytest tests

about:
  home: https://github.com/pytask-dev/pytask-r
  license: none
  summary: Run R scripts with pytask.
  dev_url: https://github.com/pytask-dev/pytask-r/
