name: zizmor

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: Scan GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: '3.13'

      - name: Run zizmor
        run: uvx --from zizmor zizmor --format=github .

      - name: Generate SARIF report
        if: always()
        run: uvx --from zizmor zizmor --format=sarif --no-exit-codes . > zizmor.sarif

      - name: Upload SARIF report
        if: >
          always() &&
          (github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository)
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4
        with:
          sarif_file: zizmor.sarif
